### ISSUE TITLE
Quantification issues

### ISSUE THREAD

**Issue by jenniferkorchak** [DICP-1809/Glyco-Decipher#7]
Hello,

I have successfully gotten the Demo data to work, but when trying to run my own data that was acquired with DDA sceHCD , I am getting stuck at the Quantification step. 
![image](https://github.com/DICP-1809/Glyco-Decipher/assets/122562006/4b538e60-d974-4ad2-8907-d29d97f85888)

When I check the output, there is nothing written in the files, even though there were appropriate outputs in the temp_ folder at the previous steps. 

Thank you!

**Comment by DICP-1809** [comment]
Please make the following check: 
1. Please first check the percentage of oxonium ion containing spectra in your data, which is shown in the search panel of Glyco-Decipher. And check the number of spectra that contain sufficient glycan core structure ions. Low oxonium ion-containing spectra means that there are not much glycopeptide spectra in your data:
![image](https://github.com/DICP-1809/Glyco-Decipher/assets/84326485/242e72d6-6614-4997-a3ee-18296accd0f6)

2. Please make sure that there are any glycopeptide results were identified in your spectrum data. You can open the "XXX__GPSM_DatabaseGlycan.txt" file to check the results. If there are no glycopeptides were identified, the quantification will also output empty results.

**Comment by jenniferkorchak** [comment]
I believe that was my issue- there was only 1 glycopeptide in the results and 19 core structure peaks.  Thank you for your quick and thorough response!
